spring:
  datasource:
    url: 
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
resilience4j:
  retry:
    instances:
      optimistic-lock-retry:
        maxAttempts: 5
        waitDuration: 1s
        retryExceptions:
          - org.springframework.orm.ObjectOptimisticLockingFailureException
        exponentialBackoff:
          multiplier: 1.5
          maxInterval: 10s
          jitter: 0.2
logging:
  level:
    io.github.resilience4j.retry: DEBUG
server:
    port: 8082
